// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: titiktopup.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PriceSell     float64                `protobuf:"fixed64,4,opt,name=price_sell,json=priceSell,proto3" json:"price_sell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_titiktopup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_titiktopup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_titiktopup_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPriceSell() float64 {
	if x != nil {
		return x.PriceSell
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Products      []*Product             `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_titiktopup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_titiktopup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_titiktopup_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_titiktopup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titiktopup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_titiktopup_proto_rawDescGZIP(), []int{2}
}

func (x *MenuResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdGame    string                 `protobuf:"bytes,1,opt,name=user_id_game,json=userIdGame,proto3" json:"user_id_game,omitempty"`
	ZoneIdGame    string                 `protobuf:"bytes,2,opt,name=zone_id_game,json=zoneIdGame,proto3" json:"zone_id_game,omitempty"`
	ProductId     uint32                 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_titiktopup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titiktopup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_titiktopup_proto_rawDescGZIP(), []int{3}
}

func (x *CheckoutRequest) GetUserIdGame() string {
	if x != nil {
		return x.UserIdGame
	}
	return ""
}

func (x *CheckoutRequest) GetZoneIdGame() string {
	if x != nil {
		return x.ZoneIdGame
	}
	return ""
}

func (x *CheckoutRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckoutRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_titiktopup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titiktopup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_titiktopup_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_titiktopup_proto protoreflect.FileDescriptor

const file_titiktopup_proto_rawDesc = "" +
	"\n" +
	"\x10titiktopup.proto\x12\n" +
	"titiktopup\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"^\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"price_sell\x18\x04 \x01(\x01R\tpriceSell\"s\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12/\n" +
	"\bproducts\x18\x04 \x03(\v2\x13.titiktopup.ProductR\bproducts\"D\n" +
	"\fMenuResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.titiktopup.CategoryR\n" +
	"categories\"\x9b\x01\n" +
	"\x0fCheckoutRequest\x12 \n" +
	"\fuser_id_game\x18\x01 \x01(\tR\n" +
	"userIdGame\x12 \n" +
	"\fzone_id_game\x18\x02 \x01(\tR\n" +
	"zoneIdGame\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\rR\tproductId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"^\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice2\xba\x01\n" +
	"\fTopupService\x12J\n" +
	"\aGetMenu\x12\x16.google.protobuf.Empty\x1a\x18.titiktopup.MenuResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/menu\x12^\n" +
	"\bCheckout\x12\x1b.titiktopup.CheckoutRequest\x1a\x1f.titiktopup.TransactionResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/checkoutBg\x92AP\x12K\n" +
	"\x13TitikTopup Core API\x12-Core backend service for TitikTopup platform.2\x051.0.0*\x01\x01Z\x12titiktopup-core/pbb\x06proto3"

var (
	file_titiktopup_proto_rawDescOnce sync.Once
	file_titiktopup_proto_rawDescData []byte
)

func file_titiktopup_proto_rawDescGZIP() []byte {
	file_titiktopup_proto_rawDescOnce.Do(func() {
		file_titiktopup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titiktopup_proto_rawDesc), len(file_titiktopup_proto_rawDesc)))
	})
	return file_titiktopup_proto_rawDescData
}

var file_titiktopup_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_titiktopup_proto_goTypes = []any{
	(*Product)(nil),             // 0: titiktopup.Product
	(*Category)(nil),            // 1: titiktopup.Category
	(*MenuResponse)(nil),        // 2: titiktopup.MenuResponse
	(*CheckoutRequest)(nil),     // 3: titiktopup.CheckoutRequest
	(*TransactionResponse)(nil), // 4: titiktopup.TransactionResponse
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_titiktopup_proto_depIdxs = []int32{
	0, // 0: titiktopup.Category.products:type_name -> titiktopup.Product
	1, // 1: titiktopup.MenuResponse.categories:type_name -> titiktopup.Category
	5, // 2: titiktopup.TopupService.GetMenu:input_type -> google.protobuf.Empty
	3, // 3: titiktopup.TopupService.Checkout:input_type -> titiktopup.CheckoutRequest
	2, // 4: titiktopup.TopupService.GetMenu:output_type -> titiktopup.MenuResponse
	4, // 5: titiktopup.TopupService.Checkout:output_type -> titiktopup.TransactionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_titiktopup_proto_init() }
func file_titiktopup_proto_init() {
	if File_titiktopup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titiktopup_proto_rawDesc), len(file_titiktopup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_titiktopup_proto_goTypes,
		DependencyIndexes: file_titiktopup_proto_depIdxs,
		MessageInfos:      file_titiktopup_proto_msgTypes,
	}.Build()
	File_titiktopup_proto = out.File
	file_titiktopup_proto_goTypes = nil
	file_titiktopup_proto_depIdxs = nil
}
